name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma-xl
    # runs-on: [self-hosted, macOS, ARM64, macstadium]
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: swift
          build-mode: manual
    steps:
    - uses: actions/checkout@v4
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2
    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
    - name: LFS pull
      run: git lfs pull
    - name: Install Postgres
      run: brew install postgresql@15
    - name: Link Postgres
      run: brew link postgresql@15
    - name: Start Postgres
      run: brew services start postgresql@15
    - name: Bootstrap
      run: make bootstrap
    
    
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}    

    - if: matrix.build-mode == 'manual'
      name: Create CodeQL Database
      run: |
        make build-client-preview-apps
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"


  # ubuntu:
  #   name: Ubuntu
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install dependencies
  #     run: 'sudo apt-get --fix-missing update && sudo apt-get install -y wamerican'
  #   - name: Bootstrap
  #     run: make bootstrap-client
  #   - name: Run tests
  #     run: make test-server-linux
